# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint-dockerfile: ## name of jobs
      executor: docker/machine
      steps:
        - checkout # Agar CircleCI memiliki akses ke code
        - docker/dockerlint:  # install dockerlint
            dockerfile: ./Dockerfile  # path dockerfile
            treat-warnings-as-errors: true ## failed if get warning
  test-app:
      docker: # base image golang
      - image: circleci/golang:1.15.8
      steps:
        - checkout # Agar CircleCI memiliki akses ke code
        - run:
            name: Run tests
            command: go test -v -short --count=1 $(go list ./...)
  build-and-push:
      executor: docker/docker 
      steps:
        - checkout
        - run:
            name: Build and push image
            command: bash build_push_image_karsajobs.sh

workflows:
  push-image:
    jobs:
      - lint-dockerfile
      - test-app
      - build-and-push