# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint-dockerfile: ## name of jobs
      executor: docker/machine
      steps:
        - checkout # Agar CircleCI memiliki akses ke code
        - docker/dockerlint:  # install dockerlint
            dockerfile: ./Dockerfile  # path dockerfile
            treat-warnings-as-errors: true ## failed if get warning
  build-app-karsajobs-ui:
      executor: docker/docker 
      steps:
        - checkout
        - setup_remote_docker #setup remote Docker engine to using docker command 
        - run:
            name: Build and push image
            command: bash build_push_image_karsajobs_ui.sh

workflows:
  push-image:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui